### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by wooorm**
Hi! :wave:

I’ve changed this rule with updated dependencies and support for the latest version of remark.

Please review carefully, I rewrote some of the internals of the rule too: some of the fixtures in the readme did now have corresponding code, so I did my best to interpret what should happen, not sure if I did so correctly though!

### CODE REVIEW

**Comment by vhf** [comment]
This is really awesome, many thanks again!

**Comment by wooorm** [comment]
Cheers, thanks for merging! 👍

Release at your leisure!

**Comment by vhf** [comment]
Released as `2.0.0`.

**Comment by wooorm** [comment]
Great, thanks! Sorry about the missing deps!

**Pull request merged**
